// This file is auto-generated by organjsm tangle. Do not edit directly.
// Source: index.org

// [[file:index.org::23207]]
import Foundation

/// Collect all values from an AsyncStream into an array.
public func collect<T>(_ stream: AsyncStream<T>) async -> [T] {
  var values: [T] = []
  for await value in stream {
    values.append(value)
  }
  return values
}

/// Collect all values from an AsyncThrowingStream into an array.
public func collectThrowing<T>(_ stream: AsyncThrowingStream<T, Error>) async throws -> [T] {
  var values: [T] = []
  for try await value in stream {
    values.append(value)
  }
  return values
}
// unnamed ends here
